export default {
    DONE_ADD_CARD: "DONE_ADD_CARD",
    DONE_DELETE_CARD: "DONE_DELETE_CARD",
    INPROGRESS_DELETE_CARD: "INPROGRESS_DELETE_CARD",
    INPROGRESS_ADD_CARD: "INPROGRESS_ADD_CARD",
    TODO_DELETE_CARD: "TODO_DELETE_CARD",
    TODO_ADD_CARD: "TODO_ADD_CARD",
}
